# Generated by Django 4.2.1 on 2023-06-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8s_excel', '0003_alter_yamllog_yaml_objects'),
    ]

    operations = [
        migrations.AddField(
            model_name='yamllog',
            name='namespace',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='yamllog',
            name='output',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
